### ISSUE TITLE
Can´t find the database

### ISSUE THREAD

**Issue by tiagoalberto** [emmagarland/eg.skrift.sample#1]
I can´t find your sample database in the project files. How can we replicate your DB?

**Comment by emmagarland** [comment]
Hi @tiagoalberto 

Sorry, just seen this somehow! 

I've been in touch with you elsewhere but thanks for getting in touch. The database is now uploaded. 

The credentials are my email and **password**: ChangeThisPassword

NB some things in Umbraco have since evolved so there may be other ways to do some of this in Umbraco now (it has been a while since I looked & we now have [Umbraco 8](https://umbraco.com/umbraco-8/)), but hopefully this helps line up the concepts in the article with the database now!

All the best

Emma

**Comment by tiagoalberto** [comment]
Amazing Emma! Thank you very much.
